using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

using EOS.Attributes;
using EOS.Entities;
using EOS.Objects;
using EOS.Systems;

namespace EOS.CodeGen
{
    /// <summary>Emits a self-installing zero-alloc system registry from the discovered <see cref="EosSystem"/> types, replacing the reflection path when present. Re-run after adding, removing or changing systems.</summary>
    public static class SystemRegistryGenerator
    {
        const string DefaultNamespace = "EOS.Generated";
        const string DefaultClassName = "EosGeneratedSystems";
        const string DefaultFileName = "EosGeneratedSystems.g.cs";

        /// <summary>Generates the registry source and writes it to <paramref name="outputDirectory"/>/<paramref name="fileName"/>; returns the written path.</summary>
        public static string Generate(
            string outputDirectory = "_Generated",
            string @namespace = DefaultNamespace,
            string className = DefaultClassName,
            string fileName = DefaultFileName)
        {
            var source = BuildSource(@namespace, className);
            Directory.CreateDirectory(outputDirectory);
            var path = Path.Combine(outputDirectory, fileName);
            File.WriteAllText(path, source);
            return path;
        }

        /// <summary>Builds and returns the generated registry C# source as a string, without writing a file.</summary>
        public static string BuildSource(string @namespace = DefaultNamespace, string className = DefaultClassName)
        {
            var systems = DiscoverSystems();
            var components = new HashSet<Type>();

            var entries = new StringBuilder();
            var binds = new StringBuilder();
            int bindId = 0;
            int eventBindId = 0;

            foreach (var type in systems)
            {
                var name = CSharpName(type);
                var methods = type
                    .GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
                    .Where(m => m.Name == "Execute" || m.Name == "EventExecute")
                    .ToArray();

                CollectComponents(methods, components);

                var invokers = new List<(string key, string lambda)>();
                var bodies = new List<(string key, string bind)>();
                var eventBodies = new List<(string key, string bind)>();
                var shapes = new List<(string key, string hash)>();

                foreach (var method in methods)
                {
                    if (!CanInvoke(method)) continue;

                    var key = SystemSignature.Of(method);
                    if (method.Name == "Execute" && SystemShape.CanTypeBody(method)
                        && AllTypesAccessible(type, method) && InterfacesEnumerable(method))
                    {
                        var bindName = "Bind_" + bindId++;
                        EmitBind(binds, bindName, name, method);
                        bodies.Add((key, bindName));
                        shapes.Add((key, Literal(SystemShape.ShapeHash(method))));
                    }
                    else if (method.Name == "EventExecute" && CanTypeEvent(method))
                    {
                        var bindName = "EventBind_" + eventBindId++;
                        EmitEventBind(binds, bindName, name, method);
                        eventBodies.Add((key, bindName));
                    }
                    else
                    {
                        invokers.Add((key, InvokerLambda(name, method)));
                    }
                }

                entries.Append("            systems.Add(new global::EOS.CodeGen.GeneratedSystem(\n");
                entries.Append("                typeof(").Append(name).Append("),\n");
                entries.Append("                () => new ").Append(name).Append("(),\n");
                AppendDictionary(entries, "global::EOS.CodeGen.SystemInvoker", invokers, ",\n");
                AppendDictionary(entries, "global::EOS.CodeGen.SystemBodyBinder", bodies, ",\n");
                AppendDictionary(entries, "global::EOS.CodeGen.EventBodyBinder", eventBodies, ",\n");
                AppendDictionary(entries, "string", shapes, "));\n");
            }

            var preserve = new StringBuilder();
            foreach (var component in components.OrderBy(CSharpName, StringComparer.Ordinal))
                preserve.Append("            world.ObjectsStorages.Get<").Append(CSharpName(component)).Append(">();\n");

            var sb = new StringBuilder();
            sb.Append("// <auto-generated>\n");
            sb.Append("// Generated by EOS SystemRegistryGenerator. Do not edit by hand.\n");
            sb.Append("// Regenerate after adding, removing or changing systems.\n");
            sb.Append("// </auto-generated>\n\n");
            sb.Append("namespace ").Append(@namespace).Append("\n{\n");
            sb.Append("    internal sealed class ").Append(className).Append(" : global::EOS.CodeGen.IGeneratedSystems\n");
            sb.Append("    {\n");
            sb.Append("        [global::System.Runtime.CompilerServices.ModuleInitializer]\n");
            sb.Append("        internal static void Register()\n");
            sb.Append("            => global::EOS.CodeGen.GeneratedSystems.Register(new ").Append(className).Append("());\n\n");
            sb.Append("        public global::System.Collections.Generic.IReadOnlyList<global::EOS.CodeGen.GeneratedSystem> Systems { get; } = Build();\n\n");
            sb.Append("        static global::System.Collections.Generic.IReadOnlyList<global::EOS.CodeGen.GeneratedSystem> Build()\n");
            sb.Append("        {\n");
            sb.Append("            var systems = new global::System.Collections.Generic.List<global::EOS.CodeGen.GeneratedSystem>(").Append(systems.Count).Append(");\n");
            sb.Append(entries);
            sb.Append("            return systems;\n");
            sb.Append("        }\n\n");
            sb.Append("        public void PreserveStorages(global::EOS.Core.World world)\n");
            sb.Append("        {\n");
            sb.Append(preserve);
            sb.Append("        }\n");
            if (binds.Length > 0)
            {
                sb.Append('\n');
                sb.Append(binds);
            }
            sb.Append("    }\n");
            sb.Append("}\n\n");
            sb.Append("#if !NET5_0_OR_GREATER && !EOS_NO_MODULE_INITIALIZER_POLYFILL\n");
            sb.Append("namespace System.Runtime.CompilerServices\n");
            sb.Append("{\n");
            sb.Append("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]\n");
            sb.Append("    internal sealed class ModuleInitializerAttribute : global::System.Attribute { }\n");
            sb.Append("}\n");
            sb.Append("#endif\n");
            return sb.ToString();
        }

        static void AppendDictionary(StringBuilder sb, string valueType, List<(string key, string value)> items, string tail)
        {
            if (items.Count == 0)
            {
                sb.Append("                null").Append(tail);
                return;
            }

            sb.Append("                new global::System.Collections.Generic.Dictionary<string, ").Append(valueType).Append(">\n");
            sb.Append("                {\n");
            foreach (var (key, value) in items)
                sb.Append("                    [").Append(Literal(key)).Append("] = ").Append(value).Append(",\n");
            sb.Append("                }").Append(tail);
        }

        sealed class Iface
        {
            public QueryParam Param;
            public int Index;
            public List<Type> Impls;
        }

        static void EmitBind(StringBuilder sb, string bindName, string systemName, MethodInfo method)
        {
            var parameters = SystemShape.Parameters(method);

            var concrete = new List<(QueryParam p, int index)>();
            var concreteByPosition = new Dictionary<int, int>();
            var ifaces = new List<Iface>();
            var ifaceByPosition = new Dictionary<int, int>();

            foreach (var p in parameters)
            {
                if (p.IsConcrete)
                {
                    int index = concrete.Count;
                    concrete.Add((p, index));
                    concreteByPosition[p.Position] = index;
                }
                else if (p.IsInterface)
                {
                    int index = ifaces.Count;
                    ifaces.Add(new Iface { Param = p, Index = index, Impls = InterfaceImpls(p.Type) });
                    ifaceByPosition[p.Position] = index;
                }
            }

            bool reactive = parameters.Any(p => p.Reactive);

            int driverConcrete = -1;
            int driverIface = -1;
            if (reactive)
            {
                foreach (var c in concrete)
                    if (c.p.Reactive && !c.p.Optional) { driverConcrete = c.index; break; }
                if (driverConcrete < 0)
                    foreach (var f in ifaces)
                        if (f.Param.Reactive && !f.Param.Optional) { driverIface = f.Index; break; }
            }

            bool interfaceDriver = reactive
                ? driverConcrete < 0 && driverIface >= 0
                : !concrete.Any(c => !c.p.Optional) && ifaces.Any(f => !f.Param.Optional);

            sb.Append("        static global::System.Action<float, ulong> ").Append(bindName).Append("(\n");
            sb.Append("            global::EOS.Systems.EosSystem system,\n");
            sb.Append("            global::EOS.Core.World world,\n");
            sb.Append("            global::EOS.Storage.IIndexedStorage[] include,\n");
            sb.Append("            global::EOS.Storage.IIndexedStorage[] exclude,\n");
            sb.Append("            global::System.Func<global::EOS.Entities.EosEntity, bool> tagMatch)\n");
            sb.Append("        {\n");
            sb.Append("            var self = (").Append(systemName).Append(")system;\n");
            foreach (var (p, index) in concrete)
                sb.Append("            var s").Append(index).Append(" = world.ObjectsStorages.Get<").Append(CSharpName(p.Type)).Append(">();\n");
            foreach (var f in ifaces)
            {
                sb.Append("            var impl").Append(f.Index).Append(" = new global::EOS.Storage.IIndexedStorage[] {");
                for (int k = 0; k < f.Impls.Count; k++)
                {
                    if (k > 0) sb.Append(',');
                    sb.Append(" world.ObjectsStorages.Get<").Append(CSharpName(f.Impls[k])).Append(">()");
                }
                if (f.Impls.Count > 0) sb.Append(' ');
                sb.Append("};\n");
            }
            if (interfaceDriver)
                sb.Append("            var seen = new global::System.Collections.Generic.HashSet<int>();\n");

            if (reactive)
            {
                sb.Append("            return (dt, cursor) =>\n");
                sb.Append("            {\n");
                if (driverConcrete >= 0)
                    EmitReactiveConcreteDriver(sb, method, parameters, concrete, concreteByPosition, ifaces, ifaceByPosition, driverConcrete);
                else
                    EmitReactiveInterfaceDriver(sb, method, parameters, concrete, concreteByPosition, ifaces, ifaceByPosition, driverIface);
                sb.Append("            };\n");
            }
            else
            {
                sb.Append("            return (dt, _) =>\n");
                sb.Append("            {\n");
                EmitNonReactive(sb, method, parameters, concrete, concreteByPosition, ifaces, ifaceByPosition, interfaceDriver);
                sb.Append("            };\n");
            }

            sb.Append("        }\n");
        }

        static void EmitNonReactive(
            StringBuilder sb, MethodInfo method, List<QueryParam> parameters,
            List<(QueryParam p, int index)> concrete, Dictionary<int, int> concreteByPosition,
            List<Iface> ifaces, Dictionary<int, int> ifaceByPosition, bool interfaceDriver)
        {
            var mandatoryConcrete = concrete.Where(c => !c.p.Optional).ToList();
            bool concreteDriver = mandatoryConcrete.Count > 0;
            bool entityScan = !concreteDriver && !interfaceDriver && parameters.Any(p => p.IsEntity);

            if (concreteDriver)
            {
                if (mandatoryConcrete.Count == 1)
                {
                    sb.Append("                global::EOS.Storage.IIndexedStorage pivot = s").Append(mandatoryConcrete[0].index).Append(";\n");
                }
                else
                {
                    sb.Append("                global::EOS.Storage.IIndexedStorage pivot = s").Append(mandatoryConcrete[0].index).Append(";\n");
                    sb.Append("                int min = s").Append(mandatoryConcrete[0].index).Append(".Count;\n");
                    for (int k = 1; k < mandatoryConcrete.Count; k++)
                    {
                        int mi = mandatoryConcrete[k].index;
                        sb.Append("                if (s").Append(mi).Append(".Count < min) { min = s").Append(mi).Append(".Count; pivot = s").Append(mi).Append("; }\n");
                    }
                }
                sb.Append("                int count = pivot.Count;\n");
                sb.Append("                for (int i = 0; i < count; i++)\n");
                sb.Append("                {\n");
                sb.Append("                    if (!pivot.IsReady(i)) continue;\n");
                sb.Append("                    var e = pivot.GetOwner(i);\n");
                EmitPerEntity(sb, "                    ", method, parameters, concrete, concreteByPosition, ifaces, ifaceByPosition);
                sb.Append("                }\n");
            }
            else if (interfaceDriver)
            {
                int driverIndex = ifaces.First(f => !f.Param.Optional).Index;
                sb.Append("                seen.Clear();\n");
                sb.Append("                var driver = impl").Append(driverIndex).Append(";\n");
                sb.Append("                for (int di = 0; di < driver.Length; di++)\n");
                sb.Append("                {\n");
                sb.Append("                    var drv = driver[di];\n");
                sb.Append("                    int dcount = drv.Count;\n");
                sb.Append("                    for (int i = 0; i < dcount; i++)\n");
                sb.Append("                    {\n");
                sb.Append("                        if (!drv.IsReady(i)) continue;\n");
                sb.Append("                        var e = drv.GetOwner(i);\n");
                sb.Append("                        if (!seen.Add(e.Id)) continue;\n");
                EmitPerEntity(sb, "                        ", method, parameters, concrete, concreteByPosition, ifaces, ifaceByPosition);
                sb.Append("                    }\n");
                sb.Append("                }\n");
            }
            else if (entityScan)
            {
                sb.Append("                foreach (var e in world.Entities.All())\n");
                sb.Append("                {\n");
                sb.Append("                    if (!e.IsActive) continue;\n");
                EmitPerEntity(sb, "                    ", method, parameters, concrete, concreteByPosition, ifaces, ifaceByPosition);
                sb.Append("                }\n");
            }
            else
            {
                sb.Append("                self.").Append(method.Name).Append('(').Append(CallArguments(parameters, concreteByPosition, ifaceByPosition)).Append(");\n");
            }
        }

        static void EmitReactiveConcreteDriver(
            StringBuilder sb, MethodInfo method, List<QueryParam> parameters,
            List<(QueryParam p, int index)> concrete, Dictionary<int, int> concreteByPosition,
            List<Iface> ifaces, Dictionary<int, int> ifaceByPosition, int driverConcrete)
        {
            var dp = concrete.First(c => c.index == driverConcrete).p;
            string sd = "s" + driverConcrete;

            if (dp.Channel == Channel.Removed)
            {
                EmitRemovedDriver(sb, method, parameters, concreteByPosition, ifaceByPosition, driverConcrete, dp, sd);
                return;
            }

            sb.Append("                if (").Append(MaxExpr(sd, dp)).Append(" <= cursor) return;\n");
            sb.Append("                int count = ").Append(sd).Append(".Count;\n");
            sb.Append("                for (int i = 0; i < count; i++)\n");
            sb.Append("                {\n");
            string ready = ReadySkip(sd, "i", dp);
            if (ready != null)
                sb.Append("                    if (!").Append(ready).Append(") continue;\n");
            sb.Append("                    if (").Append(VerExpr(sd, "i", dp)).Append(" <= cursor) continue;\n");
            EmitCascadeGate(sb, "                    ", sd, "i", dp);
            sb.Append("                    var e = ").Append(sd).Append(".GetOwner(i);\n");
            sb.Append("                    var c").Append(driverConcrete).Append(" = ").Append(sd).Append(".At(i);\n");
            EmitReactivePerEntity(sb, "                    ", method, parameters, concrete, concreteByPosition, ifaces, ifaceByPosition, driverConcrete);
            sb.Append("                }\n");
        }

        static void EmitRemovedDriver(
            StringBuilder sb, MethodInfo method, List<QueryParam> parameters,
            Dictionary<int, int> concreteByPosition, Dictionary<int, int> ifaceByPosition,
            int driverConcrete, QueryParam dp, string sd)
        {
            sb.Append("                if (").Append(sd).Append(".MaxRemoveVersion <= cursor) return;\n");
            sb.Append("                int count = ").Append(sd).Append(".RemovedCount;\n");
            sb.Append("                for (int i = 0; i < count; i++)\n");
            sb.Append("                {\n");
            sb.Append("                    if (").Append(sd).Append(".RemovedVersionAt(i) <= cursor) continue;\n");
            if (!dp.IncludeCascade)
                sb.Append("                    if (").Append(sd).Append(".RemovedCascadeAt(i)) continue;\n");
            sb.Append("                    var e = ").Append(sd).Append(".RemovedOwnerAt(i);\n");
            sb.Append("                    if (!global::EOS.CodeGen.GeneratedQuery.IncludeMatch(include, e)) continue;\n");
            sb.Append("                    if (!global::EOS.CodeGen.GeneratedQuery.ExcludeMatch(exclude, e)) continue;\n");
            sb.Append("                    if (tagMatch != null && !tagMatch(e)) continue;\n");
            sb.Append("                    ").Append(CSharpName(dp.Type)).Append(" c").Append(driverConcrete).Append(" = null;\n");
            sb.Append("                    self.").Append(method.Name).Append('(').Append(CallArguments(parameters, concreteByPosition, ifaceByPosition)).Append(");\n");
            sb.Append("                }\n");
        }

        static void EmitReactiveInterfaceDriver(
            StringBuilder sb, MethodInfo method, List<QueryParam> parameters,
            List<(QueryParam p, int index)> concrete, Dictionary<int, int> concreteByPosition,
            List<Iface> ifaces, Dictionary<int, int> ifaceByPosition, int driverIface)
        {
            var dp = ifaces.First(f => f.Index == driverIface).Param;
            sb.Append("                seen.Clear();\n");
            sb.Append("                var driver = impl").Append(driverIface).Append(";\n");
            sb.Append("                for (int di = 0; di < driver.Length; di++)\n");
            sb.Append("                {\n");
            sb.Append("                    var drv = driver[di];\n");
            sb.Append("                    if (").Append(MaxExpr("drv", dp)).Append(" <= cursor) continue;\n");
            sb.Append("                    int dcount = drv.Count;\n");
            sb.Append("                    for (int i = 0; i < dcount; i++)\n");
            sb.Append("                    {\n");
            string ready = ReadySkip("drv", "i", dp);
            if (ready != null)
                sb.Append("                        if (!").Append(ready).Append(") continue;\n");
            sb.Append("                        if (").Append(VerExpr("drv", "i", dp)).Append(" <= cursor) continue;\n");
            EmitCascadeGate(sb, "                        ", "drv", "i", dp);
            sb.Append("                        var e = drv.GetOwner(i);\n");
            sb.Append("                        if (!seen.Add(e.Id)) continue;\n");
            EmitReactivePerEntity(sb, "                        ", method, parameters, concrete, concreteByPosition, ifaces, ifaceByPosition, -1);
            sb.Append("                    }\n");
            sb.Append("                }\n");
        }

        static void EmitReactivePerEntity(
            StringBuilder sb, string indent, MethodInfo method, List<QueryParam> parameters,
            List<(QueryParam p, int index)> concrete, Dictionary<int, int> concreteByPosition,
            List<Iface> ifaces, Dictionary<int, int> ifaceByPosition, int driverConcrete)
        {
            foreach (var (cp, idx) in concrete)
            {
                if (idx == driverConcrete) continue;
                string s = "s" + idx;
                if (cp.Reactive)
                {
                    sb.Append(indent).Append("int k").Append(idx).Append(" = ").Append(s).Append(".IndexOf(e);\n");
                    if (cp.Optional)
                    {
                        sb.Append(indent).Append(CSharpName(cp.Type)).Append(" c").Append(idx).Append(" = null;\n");
                        sb.Append(indent).Append("if (k").Append(idx).Append(" >= 0");
                        if (cp.Channel != Channel.Disabled)
                            sb.Append(" && ").Append(s).Append(".IsReady(k").Append(idx).Append(")");
                        sb.Append(" && ").Append(VerExpr(s, "k" + idx, cp)).Append(" > cursor");
                        if (!cp.IncludeCascade && cp.Channel == Channel.Enabled)
                            sb.Append(" && !").Append(s).Append(".EnableCascadeAt(k").Append(idx).Append(")");
                        else if (!cp.IncludeCascade && cp.Channel == Channel.Disabled)
                            sb.Append(" && !").Append(s).Append(".DisableCascadeAt(k").Append(idx).Append(")");
                        sb.Append(")\n");
                        sb.Append(indent).Append("    c").Append(idx).Append(" = ").Append(s).Append(".At(k").Append(idx).Append(");\n");
                    }
                    else
                    {
                        string readyExpr = ReadySkip(s, "k" + idx, cp);
                        if (readyExpr != null)
                            sb.Append(indent).Append("if (k").Append(idx).Append(" < 0 || !").Append(readyExpr).Append(") continue;\n");
                        else
                            sb.Append(indent).Append("if (k").Append(idx).Append(" < 0) continue;\n");
                        sb.Append(indent).Append("if (").Append(VerExpr(s, "k" + idx, cp)).Append(" <= cursor) continue;\n");
                        EmitCascadeGate(sb, indent, s, "k" + idx, cp);
                        sb.Append(indent).Append("var c").Append(idx).Append(" = ").Append(s).Append(".At(k").Append(idx).Append(");\n");
                    }
                }
                else
                {
                    if (cp.Optional)
                        sb.Append(indent).Append(s).Append(".TryGetReady(e, out var c").Append(idx).Append(");\n");
                    else
                        sb.Append(indent).Append("if (!").Append(s).Append(".TryGetReady(e, out var c").Append(idx).Append(")) continue;\n");
                }
            }
            sb.Append(indent).Append("if (!global::EOS.CodeGen.GeneratedQuery.IncludeMatch(include, e)) continue;\n");
            sb.Append(indent).Append("if (!global::EOS.CodeGen.GeneratedQuery.ExcludeMatch(exclude, e)) continue;\n");
            sb.Append(indent).Append("if (tagMatch != null && !tagMatch(e)) continue;\n");
            EmitReactiveFanout(sb, indent, 0, method, parameters, concreteByPosition, ifaces, ifaceByPosition);
        }

        static void EmitReactiveFanout(
            StringBuilder sb, string indent, int fanoutIndex, MethodInfo method, List<QueryParam> parameters,
            Dictionary<int, int> concreteByPosition, List<Iface> ifaces, Dictionary<int, int> ifaceByPosition)
        {
            if (fanoutIndex == ifaces.Count)
            {
                sb.Append(indent).Append("self.").Append(method.Name).Append('(').Append(CallArguments(parameters, concreteByPosition, ifaceByPosition)).Append(");\n");
                return;
            }

            var f = ifaces[fanoutIndex];
            int idx = f.Index;
            string type = CSharpName(f.Param.Type);
            string inner = indent + "    ";

            if (f.Param.Each)
            {
                if (f.Param.Optional)
                    sb.Append(indent).Append("bool any").Append(idx).Append(" = false;\n");

                sb.Append(indent).Append("for (int j").Append(idx).Append(" = 0; j").Append(idx).Append(" < impl").Append(idx).Append(".Length; j").Append(idx).Append("++)\n");
                sb.Append(indent).Append("{\n");
                sb.Append(inner).Append("var st").Append(idx).Append(" = impl").Append(idx).Append("[j").Append(idx).Append("];\n");
                sb.Append(inner).Append("int ik").Append(idx).Append(" = st").Append(idx).Append(".IndexOf(e);\n");
                string ready = ReadySkip("st" + idx, "ik" + idx, f.Param);
                if (ready != null)
                    sb.Append(inner).Append("if (ik").Append(idx).Append(" < 0 || !").Append(ready).Append(") continue;\n");
                else
                    sb.Append(inner).Append("if (ik").Append(idx).Append(" < 0) continue;\n");
                if (f.Param.Reactive)
                {
                    sb.Append(inner).Append("if (").Append(VerExpr("st" + idx, "ik" + idx, f.Param)).Append(" <= cursor) continue;\n");
                    EmitCascadeGate(sb, inner, "st" + idx, "ik" + idx, f.Param);
                }
                if (f.Param.Optional)
                    sb.Append(inner).Append("any").Append(idx).Append(" = true;\n");
                sb.Append(inner).Append("var v").Append(idx).Append(" = (").Append(type).Append(")st").Append(idx).Append(".GetAt(ik").Append(idx).Append(");\n");
                EmitReactiveFanout(sb, inner, fanoutIndex + 1, method, parameters, concreteByPosition, ifaces, ifaceByPosition);
                sb.Append(indent).Append("}\n");

                if (f.Param.Optional)
                {
                    sb.Append(indent).Append("if (!any").Append(idx).Append(")\n");
                    sb.Append(indent).Append("{\n");
                    sb.Append(inner).Append(type).Append(" v").Append(idx).Append(" = null;\n");
                    EmitReactiveFanout(sb, inner, fanoutIndex + 1, method, parameters, concreteByPosition, ifaces, ifaceByPosition);
                    sb.Append(indent).Append("}\n");
                }
            }
            else
            {
                sb.Append(indent).Append(type).Append(" v").Append(idx).Append(" = null;\n");
                sb.Append(indent).Append("for (int j").Append(idx).Append(" = 0; j").Append(idx).Append(" < impl").Append(idx).Append(".Length; j").Append(idx).Append("++)\n");
                sb.Append(indent).Append("{\n");
                sb.Append(inner).Append("var st").Append(idx).Append(" = impl").Append(idx).Append("[j").Append(idx).Append("];\n");
                sb.Append(inner).Append("int ik").Append(idx).Append(" = st").Append(idx).Append(".IndexOf(e);\n");
                string ready = ReadySkip("st" + idx, "ik" + idx, f.Param);
                if (ready != null)
                    sb.Append(inner).Append("if (ik").Append(idx).Append(" < 0 || !").Append(ready).Append(") continue;\n");
                else
                    sb.Append(inner).Append("if (ik").Append(idx).Append(" < 0) continue;\n");
                if (f.Param.Reactive)
                {
                    sb.Append(inner).Append("if (").Append(VerExpr("st" + idx, "ik" + idx, f.Param)).Append(" <= cursor) continue;\n");
                    EmitCascadeGate(sb, inner, "st" + idx, "ik" + idx, f.Param);
                }
                sb.Append(inner).Append("v").Append(idx).Append(" = (").Append(type).Append(")st").Append(idx).Append(".GetAt(ik").Append(idx).Append("); break;\n");
                sb.Append(indent).Append("}\n");

                if (f.Param.Optional)
                {
                    EmitReactiveFanout(sb, indent, fanoutIndex + 1, method, parameters, concreteByPosition, ifaces, ifaceByPosition);
                }
                else
                {
                    sb.Append(indent).Append("if (v").Append(idx).Append(" != null)\n");
                    sb.Append(indent).Append("{\n");
                    EmitReactiveFanout(sb, inner, fanoutIndex + 1, method, parameters, concreteByPosition, ifaces, ifaceByPosition);
                    sb.Append(indent).Append("}\n");
                }
            }
        }

        static string MaxExpr(string storage, QueryParam p) => p.Channel switch
        {
            Channel.Bumped => storage + ".MaxMarkVersion",
            Channel.Enabled => storage + ".MaxEnableVersion",
            Channel.Disabled => storage + ".MaxDisableVersion",
            _ => storage + ".MaxAddVersion"
        };

        static string VerExpr(string storage, string indexExpr, QueryParam p) => p.Channel switch
        {
            Channel.Bumped => storage + ".MarkVersionAt(" + indexExpr + ")",
            Channel.Enabled => storage + ".EnableVersionAt(" + indexExpr + ")",
            Channel.Disabled => storage + ".DisableVersionAt(" + indexExpr + ")",
            _ => storage + ".AddVersionAt(" + indexExpr + ")"
        };

        static string ReadySkip(string storage, string indexExpr, QueryParam p)
            => p.Channel == Channel.Disabled ? null : storage + ".IsReady(" + indexExpr + ")";

        static void EmitCascadeGate(StringBuilder sb, string indent, string storage, string indexExpr, QueryParam p)
        {
            if (p.IncludeCascade) return;
            if (p.Channel == Channel.Enabled)
                sb.Append(indent).Append("if (").Append(storage).Append(".EnableCascadeAt(").Append(indexExpr).Append(")) continue;\n");
            else if (p.Channel == Channel.Disabled)
                sb.Append(indent).Append("if (").Append(storage).Append(".DisableCascadeAt(").Append(indexExpr).Append(")) continue;\n");
        }

        static bool CanTypeEvent(MethodInfo method)
        {
            if (method.Name != "EventExecute") return false;

            Type eventType = null;
            foreach (var p in method.GetParameters())
            {
                var t = p.ParameterType;
                if (t == typeof(float)) continue;
                if (!t.IsValueType || t == typeof(EosEntity)) return false;
                if (eventType != null) return false;
                eventType = t;
            }
            return eventType != null && IsAccessible(eventType);
        }

        static void EmitEventBind(StringBuilder sb, string bindName, string systemName, MethodInfo method)
        {
            var parameters = method.GetParameters();
            Type eventType = null;
            foreach (var p in parameters)
                if (p.ParameterType != typeof(float)) eventType = p.ParameterType;

            sb.Append("        static global::EOS.CodeGen.EventBinding ").Append(bindName).Append("(\n");
            sb.Append("            global::EOS.Systems.EosSystem system,\n");
            sb.Append("            global::EOS.Core.World world)\n");
            sb.Append("        {\n");
            sb.Append("            var self = (").Append(systemName).Append(")system;\n");
            sb.Append("            var ch = world.Events.Channel<").Append(CSharpName(eventType)).Append(">();\n");
            sb.Append("            int slot = ch.RegisterConsumer();\n");
            sb.Append("            global::System.Action<float> body = dt =>\n");
            sb.Append("            {\n");
            sb.Append("                ulong cursor = ch.CursorOf(slot);\n");
            sb.Append("                if (ch.MaxSeq <= cursor) return;\n");
            sb.Append("                int count = ch.LiveCount;\n");
            sb.Append("                for (int i = 0; i < count; i++)\n");
            sb.Append("                {\n");
            sb.Append("                    if (ch.SeqAt(i) <= cursor) continue;\n");
            sb.Append("                    var ev = ch.ValueAt(i);\n");
            sb.Append("                    self.").Append(method.Name).Append('(').Append(EventCallArguments(parameters)).Append(");\n");
            sb.Append("                }\n");
            sb.Append("            };\n");
            sb.Append("            return new global::EOS.CodeGen.EventBinding(body, ch, slot);\n");
            sb.Append("        }\n");
        }

        static string EventCallArguments(ParameterInfo[] parameters)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(parameters[i].ParameterType == typeof(float) ? "dt" : "ev");
            }
            return sb.ToString();
        }

        static void EmitPerEntity(
            StringBuilder sb, string indent, MethodInfo method, List<QueryParam> parameters,
            List<(QueryParam p, int index)> concrete, Dictionary<int, int> concreteByPosition,
            List<Iface> ifaces, Dictionary<int, int> ifaceByPosition)
        {
            foreach (var (p, index) in concrete)
            {
                if (p.Optional)
                    sb.Append(indent).Append("s").Append(index).Append(".TryGetReady(e, out var c").Append(index).Append(");\n");
                else
                    sb.Append(indent).Append("if (!s").Append(index).Append(".TryGetReady(e, out var c").Append(index).Append(")) continue;\n");
            }
            sb.Append(indent).Append("if (!global::EOS.CodeGen.GeneratedQuery.IncludeMatch(include, e)) continue;\n");
            sb.Append(indent).Append("if (!global::EOS.CodeGen.GeneratedQuery.ExcludeMatch(exclude, e)) continue;\n");
            sb.Append(indent).Append("if (tagMatch != null && !tagMatch(e)) continue;\n");
            EmitFanout(sb, indent, 0, method, parameters, concreteByPosition, ifaces, ifaceByPosition);
        }

        static void EmitFanout(
            StringBuilder sb, string indent, int fanoutIndex, MethodInfo method, List<QueryParam> parameters,
            Dictionary<int, int> concreteByPosition, List<Iface> ifaces, Dictionary<int, int> ifaceByPosition)
        {
            if (fanoutIndex == ifaces.Count)
            {
                sb.Append(indent).Append("self.").Append(method.Name).Append('(').Append(CallArguments(parameters, concreteByPosition, ifaceByPosition)).Append(");\n");
                return;
            }

            var f = ifaces[fanoutIndex];
            int idx = f.Index;
            string type = CSharpName(f.Param.Type);
            string inner = indent + "    ";

            if (f.Param.Each)
            {
                if (f.Param.Optional)
                    sb.Append(indent).Append("bool any").Append(idx).Append(" = false;\n");

                sb.Append(indent).Append("for (int j").Append(idx).Append(" = 0; j").Append(idx).Append(" < impl").Append(idx).Append(".Length; j").Append(idx).Append("++)\n");
                sb.Append(indent).Append("{\n");
                sb.Append(inner).Append("var o").Append(idx).Append(" = impl").Append(idx).Append("[j").Append(idx).Append("].TryGetReadyObject(e);\n");
                sb.Append(inner).Append("if (o").Append(idx).Append(" == null) continue;\n");
                if (f.Param.Optional)
                    sb.Append(inner).Append("any").Append(idx).Append(" = true;\n");
                sb.Append(inner).Append("var v").Append(idx).Append(" = (").Append(type).Append(")o").Append(idx).Append(";\n");
                EmitFanout(sb, inner, fanoutIndex + 1, method, parameters, concreteByPosition, ifaces, ifaceByPosition);
                sb.Append(indent).Append("}\n");

                if (f.Param.Optional)
                {
                    sb.Append(indent).Append("if (!any").Append(idx).Append(")\n");
                    sb.Append(indent).Append("{\n");
                    sb.Append(inner).Append(type).Append(" v").Append(idx).Append(" = null;\n");
                    EmitFanout(sb, inner, fanoutIndex + 1, method, parameters, concreteByPosition, ifaces, ifaceByPosition);
                    sb.Append(indent).Append("}\n");
                }
            }
            else
            {
                sb.Append(indent).Append(type).Append(" v").Append(idx).Append(" = null;\n");
                sb.Append(indent).Append("for (int j").Append(idx).Append(" = 0; j").Append(idx).Append(" < impl").Append(idx).Append(".Length; j").Append(idx).Append("++)\n");
                sb.Append(indent).Append("{\n");
                sb.Append(inner).Append("var o").Append(idx).Append(" = impl").Append(idx).Append("[j").Append(idx).Append("].TryGetReadyObject(e);\n");
                sb.Append(inner).Append("if (o").Append(idx).Append(" != null) { v").Append(idx).Append(" = (").Append(type).Append(")o").Append(idx).Append("; break; }\n");
                sb.Append(indent).Append("}\n");

                if (f.Param.Optional)
                {
                    EmitFanout(sb, indent, fanoutIndex + 1, method, parameters, concreteByPosition, ifaces, ifaceByPosition);
                }
                else
                {
                    sb.Append(indent).Append("if (v").Append(idx).Append(" != null)\n");
                    sb.Append(indent).Append("{\n");
                    EmitFanout(sb, inner, fanoutIndex + 1, method, parameters, concreteByPosition, ifaces, ifaceByPosition);
                    sb.Append(indent).Append("}\n");
                }
            }
        }

        static string CallArguments(List<QueryParam> parameters, Dictionary<int, int> concreteByPosition, Dictionary<int, int> ifaceByPosition)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < parameters.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                var p = parameters[i];
                if (p.IsEntity) sb.Append('e');
                else if (p.IsDelta) sb.Append("dt");
                else if (p.IsConcrete) sb.Append('c').Append(concreteByPosition[p.Position]);
                else sb.Append('v').Append(ifaceByPosition[p.Position]);
            }
            return sb.ToString();
        }

        static List<Type> InterfaceImpls(Type iface)
            => new(SystemShape.ImplementationsOf(iface));

        static bool InterfacesEnumerable(MethodInfo method)
        {
            foreach (var p in SystemShape.Parameters(method))
                if (p.IsInterface && !InterfaceFullyEnumerable(p.Type))
                    return false;
            return true;
        }

        static bool InterfaceFullyEnumerable(Type iface)
        {
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try { types = assembly.GetTypes(); }
                catch (ReflectionTypeLoadException ex) { types = ex.Types; }
                catch (Exception) { continue; }

                foreach (var type in types)
                {
                    if (type == null) continue;
                    if (!type.IsGenericTypeDefinition) continue;
                    if (!DerivesFromEosObject(type)) continue;
                    foreach (var implemented in type.GetInterfaces())
                        if (implemented == iface) return false;
                }
            }
            return true;
        }

        static bool DerivesFromEosObject(Type type)
        {
            for (var b = type; b != null && b != typeof(object); b = b.BaseType)
            {
                var normalized = b.IsGenericType ? b.GetGenericTypeDefinition() : b;
                if (normalized == typeof(EosObject)) return true;
            }
            return false;
        }

        static bool AllTypesAccessible(Type systemType, MethodInfo method)
        {
            if (!IsAccessible(systemType)) return false;
            foreach (var p in SystemShape.Parameters(method))
            {
                if (p.IsConcrete && !IsAccessible(p.Type)) return false;
                if (p.IsInterface)
                {
                    if (!IsAccessible(p.Type)) return false;
                    foreach (var impl in InterfaceImpls(p.Type))
                        if (!IsAccessible(impl)) return false;
                }
            }
            return true;
        }

        static bool IsAccessible(Type type)
        {
            if (type.IsByRef || type.IsArray) return IsAccessible(type.GetElementType());
            if (type.IsGenericType)
                foreach (var arg in type.GetGenericArguments())
                    if (!IsAccessible(arg)) return false;

            var cursor = type.IsGenericType ? type.GetGenericTypeDefinition() : type;
            while (cursor.IsNested)
            {
                if (cursor.IsNestedPrivate || cursor.IsNestedFamily) return false;
                cursor = cursor.DeclaringType;
            }
            return true;
        }

        static List<Type> DiscoverSystems()
        {
            var result = new List<Type>();
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try { types = assembly.GetTypes(); }
                catch (ReflectionTypeLoadException ex) { types = ex.Types; }
                catch (Exception) { continue; }

                foreach (var type in types)
                {
                    if (type == null) continue;
                    if (!type.IsClass || type.IsAbstract) continue;
                    if (type.IsGenericTypeDefinition) continue;
                    if (!typeof(EosSystem).IsAssignableFrom(type)) continue;
                    if (type == typeof(EosSystem)) continue;
                    result.Add(type);
                }
            }
            result.Sort((a, b) => string.CompareOrdinal(a.FullName, b.FullName));
            return result;
        }

        static void CollectComponents(MethodInfo[] methods, HashSet<Type> into)
        {
            foreach (var method in methods)
            {
                foreach (var parameter in method.GetParameters())
                {
                    var type = parameter.ParameterType;
                    if (!type.IsInterface && typeof(EosObject).IsAssignableFrom(type))
                        TryAddComponent(type, into);
                }

                foreach (var include in method.GetCustomAttributes<IncludeAttribute>(true))
                    foreach (var type in include.Types)
                        TryAddComponent(type, into);

                foreach (var exclude in method.GetCustomAttributes<ExcludeAttribute>(true))
                    foreach (var type in exclude.Types)
                        TryAddComponent(type, into);
            }
        }

        static void TryAddComponent(Type type, HashSet<Type> into)
        {
            if (type == null) return;
            if (type.IsAbstract || type.IsInterface) return;
            if (type.IsGenericTypeDefinition) return;
            if (!typeof(EosObject).IsAssignableFrom(type)) return;
            if (type.GetConstructor(Type.EmptyTypes) == null) return;
            into.Add(type);
        }

        static bool CanInvoke(MethodInfo method)
            => method.IsPublic || method.IsAssembly || method.IsFamilyOrAssembly;

        static string InvokerLambda(string systemName, MethodInfo method)
        {
            var parameters = method.GetParameters();
            var sb = new StringBuilder();
            sb.Append("(s, a) => ((").Append(systemName).Append(")s).").Append(method.Name).Append('(');
            for (int i = 0; i < parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append('(').Append(CSharpName(parameters[i].ParameterType)).Append(")a[").Append(i).Append(']');
            }
            sb.Append(')');
            return sb.ToString();
        }

        static string CSharpName(Type type)
        {
            if (type.IsByRef) return CSharpName(type.GetElementType());
            if (type.IsArray) return CSharpName(type.GetElementType()) + "[" + new string(',', type.GetArrayRank() - 1) + "]";

            if (type.IsGenericType)
            {
                var definition = type.GetGenericTypeDefinition();
                var full = definition.FullName ?? definition.Name;
                int tick = full.IndexOf('`');
                if (tick >= 0) full = full.Substring(0, tick);
                full = full.Replace('+', '.');

                var sb = new StringBuilder();
                sb.Append("global::").Append(full).Append('<');
                var args = type.GetGenericArguments();
                for (int i = 0; i < args.Length; i++)
                {
                    if (i > 0) sb.Append(',');
                    sb.Append(CSharpName(args[i]));
                }
                sb.Append('>');
                return sb.ToString();
            }

            var name = (type.FullName ?? type.Name).Replace('+', '.');
            return "global::" + name;
        }

        static string Literal(string value)
        {
            var sb = new StringBuilder(value.Length + 2);
            sb.Append('"');
            foreach (var c in value)
            {
                if (c == '\\' || c == '"') sb.Append('\\');
                sb.Append(c);
            }
            sb.Append('"');
            return sb.ToString();
        }
    }
}
