using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

using EOS.Attributes;
using EOS.Objects;
using EOS.Systems;

namespace EOS.CodeGen
{
    public static class SystemRegistryGenerator
    {
        const string DefaultNamespace = "EOS.Generated";
        const string DefaultClassName = "EosGeneratedSystems";
        const string DefaultFileName = "EosGeneratedSystems.g.cs";

        public static string Generate(
            string outputDirectory = "_Generated",
            string @namespace = DefaultNamespace,
            string className = DefaultClassName,
            string fileName = DefaultFileName)
        {
            var source = BuildSource(@namespace, className);
            Directory.CreateDirectory(outputDirectory);
            var path = Path.Combine(outputDirectory, fileName);
            File.WriteAllText(path, source);
            return path;
        }

        public static string BuildSource(string @namespace = DefaultNamespace, string className = DefaultClassName)
        {
            var systems = DiscoverSystems();
            var components = new HashSet<Type>();

            var entries = new StringBuilder();
            foreach (var type in systems)
            {
                var name = CSharpName(type);
                var methods = type
                    .GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
                    .Where(m => m.Name == "Execute" || m.Name == "EventExecute")
                    .ToArray();

                CollectComponents(methods, components);

                entries.Append("            systems.Add(new global::EOS.CodeGen.GeneratedSystem(\n");
                entries.Append("                typeof(").Append(name).Append("),\n");
                entries.Append("                () => new ").Append(name).Append("(),\n");

                var invokable = methods.Where(CanInvoke).ToArray();
                if (invokable.Length == 0)
                {
                    entries.Append("                null));\n");
                }
                else
                {
                    entries.Append("                new global::System.Collections.Generic.Dictionary<string, global::EOS.CodeGen.SystemInvoker>\n");
                    entries.Append("                {\n");
                    foreach (var method in invokable)
                    {
                        var key = Literal(SystemSignature.Of(method));
                        entries.Append("                    [").Append(key).Append("] = (s, a) => ((")
                            .Append(name).Append(")s).").Append(method.Name).Append('(')
                            .Append(Arguments(method)).Append("),\n");
                    }
                    entries.Append("                }));\n");
                }
            }

            var preserve = new StringBuilder();
            foreach (var component in components.OrderBy(CSharpName, StringComparer.Ordinal))
                preserve.Append("            world.ObjectsStorages.Get<").Append(CSharpName(component)).Append(">();\n");

            var sb = new StringBuilder();
            sb.Append("// <auto-generated>\n");
            sb.Append("// Generated by EOS SystemRegistryGenerator. Do not edit by hand.\n");
            sb.Append("// Regenerate after adding, removing or changing systems.\n");
            sb.Append("// </auto-generated>\n\n");
            sb.Append("namespace ").Append(@namespace).Append("\n{\n");
            sb.Append("    internal sealed class ").Append(className).Append(" : global::EOS.CodeGen.IGeneratedSystems\n");
            sb.Append("    {\n");
            sb.Append("        [global::System.Runtime.CompilerServices.ModuleInitializer]\n");
            sb.Append("        internal static void Register()\n");
            sb.Append("            => global::EOS.CodeGen.GeneratedSystems.Register(new ").Append(className).Append("());\n\n");
            sb.Append("        public global::System.Collections.Generic.IReadOnlyList<global::EOS.CodeGen.GeneratedSystem> Systems { get; } = Build();\n\n");
            sb.Append("        static global::System.Collections.Generic.IReadOnlyList<global::EOS.CodeGen.GeneratedSystem> Build()\n");
            sb.Append("        {\n");
            sb.Append("            var systems = new global::System.Collections.Generic.List<global::EOS.CodeGen.GeneratedSystem>(").Append(systems.Count).Append(");\n");
            sb.Append(entries);
            sb.Append("            return systems;\n");
            sb.Append("        }\n\n");
            sb.Append("        public void PreserveStorages(global::EOS.Core.World world)\n");
            sb.Append("        {\n");
            sb.Append(preserve);
            sb.Append("        }\n");
            sb.Append("    }\n");
            sb.Append("}\n\n");
            sb.Append("#if !NET5_0_OR_GREATER && !EOS_NO_MODULE_INITIALIZER_POLYFILL\n");
            sb.Append("namespace System.Runtime.CompilerServices\n");
            sb.Append("{\n");
            sb.Append("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]\n");
            sb.Append("    internal sealed class ModuleInitializerAttribute : global::System.Attribute { }\n");
            sb.Append("}\n");
            sb.Append("#endif\n");
            return sb.ToString();
        }

        static List<Type> DiscoverSystems()
        {
            var result = new List<Type>();
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try { types = assembly.GetTypes(); }
                catch (ReflectionTypeLoadException ex) { types = ex.Types; }
                catch (Exception) { continue; }

                foreach (var type in types)
                {
                    if (type == null) continue;
                    if (!type.IsClass || type.IsAbstract) continue;
                    if (type.IsGenericTypeDefinition) continue;
                    if (!typeof(EosSystem).IsAssignableFrom(type)) continue;
                    if (type == typeof(EosSystem)) continue;
                    result.Add(type);
                }
            }
            result.Sort((a, b) => string.CompareOrdinal(a.FullName, b.FullName));
            return result;
        }

        static void CollectComponents(MethodInfo[] methods, HashSet<Type> into)
        {
            foreach (var method in methods)
            {
                foreach (var parameter in method.GetParameters())
                {
                    var type = parameter.ParameterType;
                    if (!type.IsInterface && typeof(EosObject).IsAssignableFrom(type))
                        TryAddComponent(type, into);
                }

                foreach (var include in method.GetCustomAttributes<IncludeAttribute>(true))
                    foreach (var type in include.Types)
                        TryAddComponent(type, into);

                foreach (var exclude in method.GetCustomAttributes<ExcludeAttribute>(true))
                    foreach (var type in exclude.Types)
                        TryAddComponent(type, into);
            }
        }

        static void TryAddComponent(Type type, HashSet<Type> into)
        {
            if (type == null) return;
            if (type.IsAbstract || type.IsInterface) return;
            if (type.IsGenericTypeDefinition) return;
            if (!typeof(EosObject).IsAssignableFrom(type)) return;
            if (type.GetConstructor(Type.EmptyTypes) == null) return;
            into.Add(type);
        }

        static bool CanInvoke(MethodInfo method)
            => method.IsPublic || method.IsAssembly || method.IsFamilyOrAssembly;

        static string Arguments(MethodInfo method)
        {
            var parameters = method.GetParameters();
            var sb = new StringBuilder();
            for (int i = 0; i < parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append('(').Append(CSharpName(parameters[i].ParameterType)).Append(")a[").Append(i).Append(']');
            }
            return sb.ToString();
        }

        static string CSharpName(Type type)
        {
            if (type.IsByRef) return CSharpName(type.GetElementType());
            if (type.IsArray) return CSharpName(type.GetElementType()) + "[" + new string(',', type.GetArrayRank() - 1) + "]";

            if (type.IsGenericType)
            {
                var definition = type.GetGenericTypeDefinition();
                var full = definition.FullName ?? definition.Name;
                int tick = full.IndexOf('`');
                if (tick >= 0) full = full.Substring(0, tick);
                full = full.Replace('+', '.');

                var sb = new StringBuilder();
                sb.Append("global::").Append(full).Append('<');
                var args = type.GetGenericArguments();
                for (int i = 0; i < args.Length; i++)
                {
                    if (i > 0) sb.Append(',');
                    sb.Append(CSharpName(args[i]));
                }
                sb.Append('>');
                return sb.ToString();
            }

            var name = (type.FullName ?? type.Name).Replace('+', '.');
            return "global::" + name;
        }

        static string Literal(string value)
        {
            var sb = new StringBuilder(value.Length + 2);
            sb.Append('"');
            foreach (var c in value)
            {
                if (c == '\\' || c == '"') sb.Append('\\');
                sb.Append(c);
            }
            sb.Append('"');
            return sb.ToString();
        }
    }
}
